# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome', max_length=50, verbose_name='Nome')),
                ('rg', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='rg')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
    ]
